// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6rXAUDQpHwafcjAEPLslMXduRDoche2M',
    appId: '1:37141810916:web:61d6b9a91f343f110ca6f1',
    messagingSenderId: '37141810916',
    projectId: 'medicaledu-ac337',
    authDomain: 'medicaledu-ac337.firebaseapp.com',
    storageBucket: 'medicaledu-ac337.firebasestorage.app',
    measurementId: 'G-WEGS0BPKCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEg2Z0tiI8P5DC1ZsN8AgO-P7DZwAeoxY',
    appId: '1:37141810916:android:3ce44fc4faa8d3850ca6f1',
    messagingSenderId: '37141810916',
    projectId: 'medicaledu-ac337',
    storageBucket: 'medicaledu-ac337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBieiwyHDIphKp-CrhktBmukbw_vysVFBc',
    appId: '1:37141810916:ios:36d2664e8ce6c98c0ca6f1',
    messagingSenderId: '37141810916',
    projectId: 'medicaledu-ac337',
    storageBucket: 'medicaledu-ac337.firebasestorage.app',
    iosBundleId: 'com.example.medicaleduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBieiwyHDIphKp-CrhktBmukbw_vysVFBc',
    appId: '1:37141810916:ios:36d2664e8ce6c98c0ca6f1',
    messagingSenderId: '37141810916',
    projectId: 'medicaledu-ac337',
    storageBucket: 'medicaledu-ac337.firebasestorage.app',
    iosBundleId: 'com.example.medicaleduApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6rXAUDQpHwafcjAEPLslMXduRDoche2M',
    appId: '1:37141810916:web:36be6b62b83313280ca6f1',
    messagingSenderId: '37141810916',
    projectId: 'medicaledu-ac337',
    authDomain: 'medicaledu-ac337.firebaseapp.com',
    storageBucket: 'medicaledu-ac337.firebasestorage.app',
    measurementId: 'G-RYVX201SRG',
  );
}
